# Generated by Django 3.1.2 on 2021-03-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
    ]
