# Generated by Django 3.1.2 on 2021-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210321_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
