# Generated by Django 3.1.2 on 2021-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member_messages_servermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermessages',
            name='cipherText',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='servermessages',
            name='tag',
            field=models.BinaryField(),
        ),
    ]
