# Generated by Django 3.1.2 on 2021-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210321_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.BinaryField(),
        ),
    ]
