# Generated by Django 3.1.2 on 2021-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210321_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servermessages',
            name='cipherText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servermessages',
            name='tag',
            field=models.TextField(),
        ),
    ]
