# Generated by Django 3.1.7 on 2021-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210321_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='servermessages',
            name='cipherText',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='servermessages',
            name='tag',
            field=models.BinaryField(),
        ),
    ]
