# Generated by Django 3.1.7 on 2021-03-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210321_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='users',
        ),
        migrations.AddField(
            model_name='messages',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.member'),
            preserve_default=False,
        ),
    ]
