# Generated by Django 3.1.7 on 2021-03-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210321_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='users',
            new_name='userId',
        ),
    ]
